### PR TITLE
Added donut.lua

### PR DESCRIPTION
**Pull request by Yui-Koi**
## Description

Ideal you have Lua installed on your system. If it's not already installed, you can download and install it from the official [Lua website](https://www.lua.org/download.html). After that run
```bash
lua donut.lua
```

## Checklist
-  [x] I have read and followed the [instructions](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#how-do-i-contribute) in the README
- [x] I read and followed the [basic rules](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#basic-rules) and [recommendations](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#recommendations)
- [x] I have put the language I am adding in the name of this PR
- [x] I have created a file named `donut` in the `donuts` folder with the proper file extension
- [x] I have added a new key/value pair to `info.json` with the [proper metadata](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#step-2-submit-your-donut)

### CODE REVIEW

**Comment by IOKG04** [comment]
just asking, why did you have to update info.json so much

**Comment by Yui-Koi** [comment]
I had to commit to info.json an ungodly amount of times because my code editor would not register tabs and spaces properly. So, I had to go to GitHub and visually see the difference as the preview also didn't seem to work properly at finding the difference meaning it was completely misaligned. I've replaced all the tabs to spaces currently in my PR but I think this should be specified in the `README.md` file

**Comment by IOKG04** [comment]
ah okay

**Comment by EvanZhouDev** [comment]
LOL the info.json updates...

lgtm, thanks for contributing!

**Pull request merged**
