### PR TITLE
Adding donut.pseudo written in A-Level CS pseudocode, a didactic language used in the british curriculum.  For more information on the language, refer to https://github.com/SingularityT3/PseudoEngine2/blob/master/Syntax.md.

### PR DESCRIPTION
**Pull request by MustafaAamir**
## Description
*.pseudo files can only run with the interpreter downloaded from https://github.com/SingularityT3/PseudoEngine2. Build this project and pass donut.pseudo as an argument to the executable.

Q: If you contributing an Aternate-Implementation Donut, let me know why it is worthy of being added/why it is unique.

It's a pretty esoteric language that only exists on paper, so it's fun to see stuff being done w it.

## Checklist
- [x] I have read and followed the [instructions](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#how-do-i-contribute) in the README
    - [x] I read and followed the [basic rules](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#basic-rules) and [recommendations](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#recommendations)
- [x] I have put the language I am adding in the name of this PR
- [x] I have created a file named `donut` in the `donuts` folder with the proper file extension
- [x] I have added a new key/value pair to `info.json` with the [proper metadata](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#step-2-submit-your-donut) (Including `description` for [Alternate-Implementation Donuts](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#alternate-implementation-donuts))

### CODE REVIEW

**Comment by MustafaAamir** [comment]
It's not showing the description for some reason, so i'll write it out here. To run donut.pseudo, download the interpreter from https://github.com/SingularityT3/PseudoEngine2. Build the project and pass donut.pseudo as cli-arg to the executable.

It's a pretty esoteric language that only exists on paper, so it's fun to a see something interesting being done with it. It's hard to conceptualize a language being turing complete if it only exists on paper.

**Comment by NameGoesThere** [comment]
🔥 
good luck actually getting someone to see your pull request though.

**Comment by EvanZhouDev** [comment]
@MustafaAamir This is awesome, but ideally, to keep with `donut.c` tradition, the code must be donut-shaped... I don't know if this is this possible with the compiler, but you can see my `donut.py` for some examples of formatting code with the off-side rule

**Comment by MustafaAamir** [comment]
Yes i realize that now. It won't be possible w pseudocode because it's a stupid language :D. Cheers mate, love the repo.

**Pull request closed without merging**
