### PR TITLE
🆕🍩🍇🍉❗ (Emojicode)

### PR DESCRIPTION
**Pull request by joeskeen**
## Description
Please read [my blog post](https://dev.to/joeskeen/-donutc-but-emojicode-50k3) for more information on how I did this.

## Checklist
- [x] I have read and followed the [instructions](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#how-do-i-contribute) in the README
    - [x] I read and followed the [basic rules](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#basic-rules) and [recommendations](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#recommendations)
- [x] I have put the language I am adding in the name of this PR
- [x] I have created a file named `donut` in the `donuts` folder with the proper file extension (well, I did name it 🍩.🍇 to keep with the Emojicode convention)
- [x] I have added a new key/value pair to `info.json` with the [proper metadata](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#step-2-submit-your-donut)

### CODE REVIEW

**Comment by IOKG04** [comment]
Might I suggest making the name of the donut generating file `donut.🍇` and the key (in `info.json`) be `🍇` instead of `emojicode` so it follows the standards set in readme?  
Would probably make it a lot easier to create an automated tool to find and display the different donut programs.

Otherwise this is a great esoteric donut though :+1:

**Comment by joeskeen** [comment]
@EvanZhouDev I've made the requested changes; ready to merge?

**Comment by EvanZhouDev** [comment]
Sorry, was on mobile before 😅

Can you fix the right side of the donut a little bit? It’s a bit wavy right now… Thanks!

**Comment by joeskeen** [comment]
@EvanZhouDev 

As I mentioned in my blog post, one of the challenges of getting a good donut shape when emoji are involved is the fact that it isn't fixed-width. As you can see in this screenshot, the code looks OK, but the preview on the right (using fixed-width pixels) makes it look very not right. Unfortunately I'm unsure how I could fix the preview and the rendered at the same time.

image

Curious: what device/browser does it look weird in?

**Comment by EvanZhouDev** [comment]
It just looks slightly off in GitHub. Apologies for not reading the blog. In that case, I’ll just merge it. If you do want to fix it later, feel free to follow up a PR :)

Thank you for contributing!

**Pull request merged**
