### PR TITLE
SVG

### PR DESCRIPTION
**Pull request by joeskeen**
## Description

A simple SVG of a glazed doughnut.

## Checklist
- [x] I have read and followed the [instructions](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#how-do-i-contribute) in the README
    - [x] I read and followed the [basic rules](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#basic-rules) and [recommendations](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#recommendations)
- [x] I have put the language I am adding in the name of this PR
- [x] I have created a file named `donut` in the `donuts` folder with the proper file extension
- [x] I have added a new key/value pair to `info.json` with the [proper metadata](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#step-2-submit-your-donut)

### CODE REVIEW

**Comment by EvanZhouDev** [comment]
This might be a bit of a stretch, but @IOKG04, what do you think?

(It’s technically supposed to be a donut.c clone 😅)

**Comment by joeskeen** [comment]
Can you think of any way to animate an SVG without JS?

**Comment by joeskeen** [comment]
nvm, I just discovered you CAN animate SVGs! :exploding_head:

**Comment by EvanZhouDev** [comment]
Yep, it appears you [can](https://stackoverflow.com/questions/40258712/svg-animate-without-css-and-js)… if you can pull this off, definitely getting featured in a future video, if you let me ;)

Edit: Going to be really hard though, as you may have to do the text individually, frame by frame(?)

**Comment by joeskeen** [comment]
As long as I get the credit ;) I'm an aspiring YouTube creator as well.

**Comment by EvanZhouDev** [comment]
Of course I’ll give credit! You can make the video if you want to…

**Comment by joeskeen** [comment]
I'd love to collab!

**Comment by EvanZhouDev** [comment]
Let’s make the donut first ;)

I won’t get a good chance to focus on this until the weekends though

**Comment by joeskeen** [comment]
As requested, the SVG now looks more like the donut.c output, as it spins around. I can't express how crazy this was to implement - SVG is not meant to do anything 3D. Luckily through trial and error I figured out how to get CSS to animate it the way I wanted it - but still keeping it pure SVG without HTML.

I could see myself using this SVG as a loading spinner...

I'm going to bed now. :)

**Comment by IOKG04** [comment]
Though not the typical ascii donut im used to, this is still really interesting.

I dont see a reason not to add it :D

**Comment by EvanZhouDev** [comment]
Sure! I'll add it... may make some modifications to it later and put it as a PR for y'all to see :)

**Pull request merged**
