### PR TITLE
I added Donutv2.ps1 for PowerShell. The other PowerShell one is very slow, like very slow, and barely works.

### PR DESCRIPTION
**Pull request by jh1sc**
## Checklist
- [x] I have read and followed the [instructions](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#how-do-i-contribute) in the README
    - [x] I read and followed the [basic rules](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#basic-rules) and [recommendations](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#recommendations)
- [x] I have put the language I am adding in the name of this PR
- [x] I have created a file named `donut` in the `donuts` folder with the proper file extension
- [x] I have added a new key/value pair to `info.json` with the [proper metadata](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#step-2-submit-your-donut) (Including `description` for [Alternate-Implementation Donuts](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#alternate-implementation-donuts))

### CODE REVIEW

**Comment by IOKG04** [comment]
Please follow the naming conventions (so name your file `donut.v2.ps1` or something similar) and correct the `info.json` as explained [here](https://github.com/EvanZhouDev/TheDonutProject#step-2-submit-your-donut).  
Also I think you should still leave in the original powershell implementation in the `info.json` (unless the person who made it gave you permission to overwrite it) seeing how it still exists.

**Comment by IOKG04** [comment]
Also if you don't mind me asking, is there a reason as to why you needed to re-upload every single file?

**Comment by EvanZhouDev** [comment]
Any updates? Closing otherwise...

**Comment by EvanZhouDev** [comment]
Closing, feel free to reopen :)

**Pull request closed without merging**
