### PR TITLE
Added Rust code

### PR DESCRIPTION
**Pull request by veryloooong**
## Description

Run it either by compiling with `rustc`, putting it into a Cargo environment and using `cargo run`, or do it online with the [Rust Playground](https://play.rust-lang.org/).

## Checklist
- [x] I have read and followed the [instructions](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#how-do-i-contribute) in the README
    - [x] I read and followed the [basic rules](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#basic-rules) and [recommendations](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#recommendations)
- [x] I have put the language I am adding in the name of this PR
- [x] I have created a file named `donut` in the `donuts` folder with the proper file extension
- [x] I have added a new key/value pair to `info.json` with the [proper metadata](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#step-2-submit-your-donut)

### CODE REVIEW

**Comment by ThatXliner** [comment]
That's funny, I'm doing Rust as well https://github.com/ThatXliner/TheDonutProject/tree/patch-1

**Comment by EvanZhouDev** [comment]
@veryloooong I will most likely add @ThatXliner's version, as he did make that himself... correct me if I'm wrong, but you found another developer's donut, right?

Thank you for contributing either way!

**Comment by veryloooong** [comment]
Yeah, that's perfectly fine

**Comment by fakebhai** [comment]
> @veryloooong I will most likely add @ThatXliner's version, as he did make that himself... correct me if I'm wrong, but you found another developer's donut, right?
> 
> Thank you for contributing either way!

can't you just put them in language named folder and have multiple of them?
this should continue the repo and maybe we'll see some more fancy donuts in the future

edit: https://github.com/EvanZhouDev/TheDonutProject#alternate-implementation-donuts
or maybe as you described here

**Comment by ThatXliner** [comment]
> > @veryloooong I will most likely add @ThatXliner's version, as he did make that himself... correct me if I'm wrong, but you found another developer's donut, right?
> > Thank you for contributing either way!
> 
> can't you just put them in language named folder and have multiple of them? this should continue the repo and maybe we'll see some more fancy donuts in the future
> 
> edit: https://github.com/EvanZhouDev/TheDonutProject#alternate-implementation-donuts or maybe as you described here

That statement didn’t exist before Evan’s original comment was made. But I agree

**Pull request closed without merging**
