### PR TITLE
Made the run command for donut.sb3 actually work

### PR DESCRIPTION
**Pull request by NameGoesThere**
This just changes the start command for donut.sb3 to work (windows only)

### CODE REVIEW

**Comment by NameGoesThere** [comment]
kinda sad to see this project die ):

**Comment by EvanZhouDev** [comment]
I'm back... it's just that there wasn't much activity here anyway 😅

**Comment by NameGoesThere** [comment]
Thanks for merging it!

**Comment by NameGoesThere** [comment]
Just looked back at this and realized I forgot the commas

**Comment by EvanZhouDev** [comment]
Haha wow at this rate you're more devoted to this than I am! Feel free to PR if you want :)

Though this was supposed to be a community-powered project... I've done more than enough donuts for a lifetime 😅

**Pull request merged**
