### PR TITLE
Brainfuck

### PR DESCRIPTION
**Pull request by drakeerv**
## Description

It is heavily dependent on the speed of you cpu but I recommend brainwhat as it is what I tested it on. I have to manually do a ton of math to slow the interpreter down. 

## Checklist
- [x] I have read and followed the [instructions](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#how-do-i-contribute) in the README
    - [x] I read and followed the [basic rules](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#basic-rules) and [recommendations](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#recommendations)
- [x] I have put the language I am adding in the name of this PR
- [x] I have created a file named `donut` in the `donuts` folder with the proper file extension
- [x] I have added a new key/value pair to `info.json` with the [proper metadata](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#step-2-submit-your-donut) (Including `description` for [Alternate-Implementation Donuts](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#alternate-implementation-donuts))

### CODE REVIEW

**Comment by IOKG04** [comment]
Not bad

**Comment by IOKG04** [comment]
Also how did you make this? Cause if you wrote all of this by hand, I... I am sorry for your keyboard

**Comment by drakeerv** [comment]
> Also how did you make this? Cause if you wrote all of this by hand, I... I am sorry for your keyboard

I did the same thing that @EvanZhouDev did for the ascii svg. Here are the steps I took:

1. I found a [text to brainf converter ](https://copy.sh/brainfuck/text.html)and I inputed the following chars: "\n .,-~:;=!*#$@". I then modified it to save each char in the first 14 cells of storage.
```bf
set up chars
++++++++++>
>++++[-<++++++++>]
>++[------<+>]<+++>
>++[------<+>]<+>
>++[------<+>]<++>
>--[--<+>]<->
>+[---------<+>]<+>
>+[---------<+>]<++>
>----[----<+>]<-->
>++++[-<++++++++>]<+>
>++[------<+>]<->
>--[-------<++>]<->
>--[-------<++>]
>----[----<+>]<+
```
2. I wrote some js code similar to the svg ascii where it takes 120 snapshots of the donut and keep track of where the pointer is and move it if it not correct. (the original version reset the pointer to 0 ever print so this is a lot more efficient). I then save it to a file.
```js
const lookup_table = [
    "\n",
    " ",
    ".",
    ",",
    "-",
    "~",
    ":",
    ";",
    "=",
    "!",
    "*",
    "#",
    "$",
    "@"
]

//open file with node
const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'out.bf');

let brainf_code = "";
for (let i = 0; i < 120; i++) {
    const frame = a();
    let last_index = lookup_table.length - 1;

    function add_char(char) {
        let char_index = lookup_table.indexOf(char);
        let diff = char_index - last_index;
        if (diff > 0) {
            brainf_code += ">".repeat(diff);
        } else if (diff < 0) {
            brainf_code += "<".repeat(-diff);
        }
        brainf_code += "."
        last_index = char_index
    }
    
    brainf_code += "frame " + i
    for (let j = 0; j < frame.length; j++) {
        add_char(frame[j])
    }

    brainf_code += "\n"
}

// write to file
fs.writeFileSync(filePath, brainf_code);
```
3. This ran however the interpreter was super fast so I had to go back and add some brainf code to slow it down. I wrote a recursive function in js to generate it and add it on to the end of each frame. (I found 3 recursions worked best on my pc)
```js
const brainf_waste_time = (n) => {
    if (n == 0) return ""
    return `>-[>+${brainf_waste_time(n-1)}<-]>+<<`
}
```
4. After all this was working I just put [] arround the animation and the brainf part was done.
5. I then rewrote the donut generator to take an in file and put each char in a spot instead of just "." (This is what #35 does)
```py
inside_r = 0
outside_r = 0

with open("finished.bf", "r") as file:
    program = file.read().replace("\n", "")
    char_count = len(program)

    outside_r = int(math.sqrt((2 * char_count) / (0.8775 * math.pi))) + 1
    inside_r = int(outside_r * 0.35)

    print(f"Outer radius:\t\t\t{outside_r}\nInner radius:\t\t\t{inside_r}\n")

    buffer = [" "] * (outside_r * outside_r * 2)
    character_amount = printcircle(outside_r, buffer, outside_r * 2, ".")
    character_amount -= printcircle(inside_r, buffer, outside_r * 2, " ")

    out_string = ""
    i = 0
    for y in range(outside_r):
        for x in range(outside_r * 2):
            char = buffer[x + y * 2 * outside_r]
            if char == "." and i < char_count:
                out_string += program[i]
                i += 1
            else:
                out_string += char
        out_string += "\n"

    with open("donuts/donut.bf", "w") as file:
        print(out_string, file=file)

    print(f"\nCharacter count: {character_amount}")
```

**Comment by EvanZhouDev** [comment]
This lags out my M1 Mac to open on gh 😆

This looks _amazing_! Thank you for your contribution!

**Comment by EvanZhouDev** [comment]
I like how this project is mostly brainf now—not complaining! Let's see if it can still be on top after the SVG one comes in

**Pull request merged**
