### PR TITLE
Better developer experience

### PR DESCRIPTION
**Pull request by IOKG04**
## Description
Added the function to automatically generate a donut with a minimum amount of characters to `donut_generator` and made documentation for the tool.
I also made `README.md` link to the documentation and specified to use 4 space indentation in `info.json` so it looks more cohesive.

## Checklist
Does not apply, as this isnt a donut.

### CODE REVIEW

**Comment by EvanZhouDev** [comment]
Hello! Thank you for helping out so much… greatly appreciated. I’ll probably end up opening a Slack for this or something; would you be interested in working on the website for this with me as well?

Either way, this looks great! Maybe transpile the C into python so that it’s easier for people who are not familiar with `gcc` and stuff to use? I can do that too, if you want :)

**Comment by IOKG04** [comment]
Not really a web developer so I cant help with the website and I'm also a pretty bad python coder, so I cant really transpile my code either, sorry.

**Comment by IOKG04** [comment]
I could however help with merging the pull requests so that development can continue even when you arent able to do that.

**Comment by EvanZhouDev** [comment]
I should be able to handle it for now... anyway, I'll merge this first

**Comment by EvanZhouDev** [comment]
Again, thank you for helping... I'll be looking forward to seeing your future contributions :)

**Pull request merged**
