### PR TITLE
donut.html

### PR DESCRIPTION
**Pull request by thecolorblocks**
## Checklist
- [x] I have read and followed the [instructions](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#how-do-i-contribute) in the README
    - [x] I read and followed the [basic rules](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#basic-rules) and [recommendations](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#recommendations)
- [x] I have put the language I am adding in the name of this PR
- [x] I have created a file named `donut` in the `donuts` folder with the proper file extension
- [x] I have added a new key/value pair to `info.json` with the [proper metadata](https://github.com/EvanZhouDev/TheDonutProject?tab=readme-ov-file#step-2-submit-your-donut)

### CODE REVIEW

**Comment by IOKG04** [comment]
You still need to make you code donut shaped.

Otherwise this looks good though :+1:

**Comment by EvanZhouDev** [comment]
I think the JS he linked to is donut-shaped... I would prefer if the js was directly in the html 😅

But either way, as Rue said, we do need the html to be donut shaped, CDN or not

**Comment by thecolorblocks** [comment]
Oh html donut is possible? Will see.

**Comment by thecolorblocks** [comment]
@IOKG04 @EvanZhouDev 

Ok I have updated the html to DONUT shape. Cheers :)

**Comment by EvanZhouDev** [comment]
Looks great.

Thanks for your contribution!

**Pull request merged**
